---
title: "Run flashier on Autoimmune GWAS data"
output: workflowr::wflow_html
author: "Zining Qi"
editor_options: 
  chunk_output_type: console
---

```{r}
library(tools)
library(Matrix)
#library(NNLM)
library(fastTopics)
library(flashier)
library(ggplot2)
load("../data/beta_matrix.RData")
```

## Overview of Multi-trait data

```{r}
head(beta_matrix)
Y <- as.matrix(beta_matrix)
```

Rows are variants and columns are trait, i.e. autoimmune disease.


## Fit an semi-NMF using flashier.
# I initially set var_type = 0 to increase the number of factors discovered.

```{r}
var_per_trait <- apply(beta_matrix, 2, var, na.rm = TRUE)

# Set a lower bound (e.g., 10% of the smallest observed variance)
s1 <- 0.1 * min(var_per_trait, na.rm = TRUE)
```


```{r}
t0 <- proc.time()
fl0 <- flash(Y,ebnm_fn = c(ebnm_point_laplace, ebnm_point_exponential),
             var_type = 0,
             greedy_Kmax = 40,nullcheck = FALSE,backfit = FALSE,
             verbose = 3)
fl_snmf <- flash_init(Y,var_type = 2,S = s1)
fl_snmf <- flash_factors_init(fl_snmf,fl0,ebnm_fn = c(ebnm_point_laplace, ebnm_point_exponential))
fl_snmf <- flash_backfit(fl_snmf,extrapolate = FALSE,maxiter = 100,verbose = 3)
fl_snmf <- flash_backfit(fl_snmf,extrapolate = TRUE,maxiter = 100,verbose = 3)
t1 <- proc.time()
timings$fl_snmf <- t1 - t0
print(timings$fl_snmf)
```


## Fit an Laplace MF using flashier.
# I initially set var_type = 0 to increase the number of factors discovered.

```{r}
t0 <- proc.time()
fl0_mf <- flash(Y,ebnm_fn = c(ebnm_point_laplace, ebnm_point_laplace),
             var_type = 0,
             greedy_Kmax = 40,nullcheck = FALSE,backfit = FALSE,
             verbose = 3)
fl_mf <- flash_init(Y,var_type = 2,S = s1)
fl_mf <- flash_factors_init(fl_mf,fl0_mf,ebnm_fn = c(ebnm_point_laplace, ebnm_point_laplace))
fl_mf <- flash_backfit(fl_mf,extrapolate = FALSE,maxiter = 100,verbose = 3)
fl_mf <- flash_backfit(fl_mf,extrapolate = TRUE,maxiter = 100,verbose = 3)
t1 <- proc.time()
timings$fl_mf <- t1 - t0
print(timings$fl_mf)
```


```{r}
fl_mf_ldf   <- ldf(fl_mf,type = "i")
fl_snmf_ldf  <- ldf(fl_snmf,type = "i")
save(fl_snmf_ldf, file = "output/immune_snmf_factors.RData")
save(fl_mf_ldf, file = "output/immune_mf_factors.RData" )
```


## Explore factors identified

```{r}
load("../output/immune_mf_factors.RData")
load("../output/immune_snmf_factors.RData")
```


```{r}
traits <- colnames(Y)
F <- fl_snmf_ldf$F
k <- ncol(F)
colnames(F) <- paste0("k",1:k)
trait_factors <- c(1:k)
traits <-
 factor(traits,
        c("celiac_disease", "psoriasis", "rheumatoid_arthritis",
          "ankylosing_spondylitis", "multiple_sclerosis", "inflammatory_bowel_disease",
          "crohns_disease", "ulcerative_colitis", "systemic_lupus_erythematosus",
          "biopolar_disorder", "type_1_diabetes"))
p1 <- structure_plot(F,topics = trait_factors, 
                     grouping = traits,
                     gap = 3,
                     perplexity = 70,
                     n = 500) +
  labs(y = "membership",title = "trait factors",
       fill = "factor",color = "factor") 
```


```{r}
F <- fl_mf_ldf$F
k <- ncol(F)
colnames(F) <- paste0("k",1:k)
trait_factors <- c(1:8)
traits <-
 factor(traits,
        c("celiac_disease", "psoriasis", "rheumatoid_arthritis",
          "ankylosing_spondylitis", "multiple_sclerosis", "inflammatory_bowel_disease",
          "crohns_disease", "ulcerative_colitis", "systemic_lupus_erythematosus",
          "biopolar_disorder", "type_1_diabetes"))
p2 <- structure_plot(F,topics = trait_factors, 
                     #grouping = traits,
                     gap = 3,
                     #perplexity = 70,
                     n = 500) +
  labs(y = "membership",title = "trait factors",
       fill = "factor",color = "factor") 

plot_grid(p1,p2,nrow = 2,ncol = 1)
```



```{r}
fit <- F
# Check if 'fit' is a matrix or model object
if (is.matrix(fit)) {
  L   <- fit
  F   <- matrix(1, nrow(L), ncol(L))
  fit <- list(F = F, L = L)
  class(fit) <- "poisson_nmf_fit"
} else {
  if (!(inherits(fit, "poisson_nmf_fit") | inherits(fit, "multinom_topic_model_fit")))
    stop("Invalid input class.")
  if (inherits(fit, "poisson_nmf_fit"))
    fit <- poisson2multinom(fit)  # Assume this function exists
}

n0 <- nrow(fit$L)  # Number of samples
k  <- ncol(fit$L)   # Number of topics

if (is.null(colnames(fit$L)))
  colnames(fit$L) <- paste0("k", 1:k)

if (missing(topics))
    topics <- order(colMeans(fit$L))
if (!is.character(topics))
    topics <- colnames(fit$L[,topics,drop = FALSE])
if (!(length(topics) > 1 & all(is.element(topics,colnames(fit$L)))))
    stop("Input argument \"topics\" should be a subset of at least two ",
         "topics (columns of fit$L) specified by their names or column ",
         "indices")

if (missing(grouping))
    grouping <- factor(rep(1,n0))
if (!is.factor(grouping))
    grouping <- as.factor(grouping)
if (length(grouping) != n0)
    stop("Input argument \"grouping\" should be a factor with one entry ",
         "for each row of fit$L")

colors9 <- c("#e41a1c","#377eb8","#4daf4a","#984ea3","#ff7f00",
               "#ffff33","#a65628","#f781bf","#999999")

if (missing(colors)) {
    if (k < 10)
      colors <- colors9
    else if (k < 22)
      colors <- kelly()[-1]
    else      
      colors <- glasbey()[-1]
}
if (length(colors) < k)
    stop("There must be at least as many colours as topics")

names(colors) <- colnames(fit$L)
colors <- colors[topics]
n <- 500
loadings_order <- "embed"


embed_method <- function(fit) {
if (nrow(fit$L) < 20) {
    return(rnorm(nrow(fit$L)))
} else {
    d <- dim(fit$L)
    message(sprintf("Running tsne on %s x %s matrix.",d[1],d[2]))
    return(drop(suppressMessages(tsne_from_topics(fit,dims = 1,...))))
  }
}

if (all(loadings_order == "embed")) {

    # If necessary, randomly subsample the rows of L.
    if (n < n0) {
      rows <- sample(n0,n)
      fit <- select_loadings(fit,rows)
      grouping <- grouping[rows,drop = FALSE]
    }

    # The ordering of the rows is not provided, so determine an
    # ordering by computing a 1-d embedding of L.
    if (nlevels(grouping) == 1) {
      y <- embed_method(fit)
      loadings_order <- order(y)
    } else {
      loadings_order <- NULL
      for (group in levels(grouping)) {
        i <- which(grouping == group)
        if (length(i) > 0)
          y <- embed_method(select_loadings(fit,i),...)
        loadings_order <- c(loadings_order,i[order(y)])
      }
    }
  } else {
    if (!missing(n))
      warning("Input argument \"n\" is ignored when \"loadings_order\" is ",
              "not \"embed\"")
    if (is.character(loadings_order))
      loadings_order <- match(loadings_order,rownames(fit$L))
}

fit$L <- fit$L[loadings_order,]
grouping <- grouping[loadings_order,drop = TRUE]

compile_structure_plot_data <- function (L, topics) {
  n <- nrow(L)
  k <- length(topics)
  dat <- data.frame(sample = rownames(fit$L),
                    topic  = rep(topics,each = n),
                    prop   = c(L[,topics]))
  dat$topic <- factor(dat$topic,topics)
  return(dat)
}

dat <- compile_structure_plot_data(fit$L,topics)

structure_plot_ggplot_call <- function (dat, colors, ticks = NULL,
                                        font.size = 9, linewidth = 3) {
  ggplot(dat,aes_string(x = "sample",y = "prop",fill = "topic")) +
    geom_col(linewidth = linewidth,width = 0.9) +
    #scale_x_continuous(limits = c(0,max(dat$sample) + 1),breaks = ticks,
                       #labels = names(ticks)) +
    scale_fill_manual(values = colors) +
    labs(x = "",y = "membership") +
    theme_cowplot(font.size) +
    theme(axis.line   = element_blank(),
          axis.ticks  = element_blank(),
          axis.text.x = element_text(angle = 45,hjust = 1))
}
p1 <- structure_plot_ggplot_call(dat,colors)
p2 <- structure_plot_ggplot_call(dat,colors)

plot_grid(p1,p2,nrow = 2,ncol = 1)
```





